# Generated by Django 3.2 on 2022-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
